apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: fullstack-app
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "fullstack_prod"
  NODE_ENV: "production"
  PORT: "4000"
  LOG_LEVEL: "error"
  VITE_API_URL: "http://backend.prod.fullstack-app.local"
