apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fullstack-prod

resources:
  - ../../base
  - hpa.yaml

patchesStrategicMerge:
  - patch-replicas.yaml
  - patch-resources.yaml
  - patch-ingress.yaml
  - patch-backend-secret-env.yaml
  - configmap.yaml
  - secret.yaml

images:
  - name: mogobanyamwaro/nest-backend
    newTag: 1.0.0
  - name: mogobanyamwaro/react-frontend
    newTag: 1.0.0
