apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: fullstack-app
type: Opaque
stringData:
  POSTGRES_USER: staging_user
  POSTGRES_PASSWORD: staging_pass456
  POSTGRES_DB: fullstack_staging
